language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
services:
  - redis-server
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
# command to run tests
script: python manage.py test

after_success: 
  - bash <(curl -s https://codecov.io/bash)
